"""
models/catalog.py
=================
Pydantic model for the complete API catalogue generated by Phase 1.

The ``APICatalog`` model is the top-level container that aggregates all
discovered ``EndpointModel`` instances together with scan-level metadata.

Phase 2 (Security Testing Agent) loads this file directly and iterates
``endpoints`` to build its test plan, so the structure must remain stable.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from models.endpoint import EndpointModel, RiskLevel, EndpointCategory, HTTPMethod


# ---------------------------------------------------------------------------
# Statistics model
# ---------------------------------------------------------------------------

class CatalogStats(BaseModel):
    """
    Aggregated statistics derived from the discovered endpoints.

    Computed at catalogue generation time so Phase 2 can use them
    without re-scanning.
    """

    total_endpoints: int = Field(default=0, description="Total unique endpoint/method pairs.")
    declared_operations_count: int = Field(
        default=0, description="Count of operations explicitly declared in OpenAPI spec."
    )
    supported_operations_count: int = Field(
        default=0, description="Count of operations supported by the server (status 2xx, 400, 401, 403)."
    )
    unsupported_probed_count: int = Field(
        default=0, description="Count of probed methods rejected with 405 Method Not Allowed."
    )
    by_method: Dict[str, int] = Field(
        default_factory=dict,
        description="Endpoint count grouped by HTTP method.",
    )
    by_category: Dict[str, int] = Field(
        default_factory=dict,
        description="Endpoint count grouped by functional category.",
    )
    by_risk: Dict[str, int] = Field(
        default_factory=dict,
        description="Endpoint count grouped by inherent risk level.",
    )
    by_discovery_method: Dict[str, int] = Field(
        default_factory=dict,
        description="Endpoint count grouped by how they were discovered.",
    )
    authenticated_endpoints: int = Field(
        default=0,
        description="Number of endpoints that require authentication.",
    )
    unauthenticated_endpoints: int = Field(
        default=0,
        description="Number of endpoints with no authentication.",
    )

    @classmethod
    def from_endpoints(cls, endpoints: List[EndpointModel]) -> "CatalogStats":
        """
        Compute statistics from a list of endpoints.
        """
        by_method: Dict[str, int] = {}
        by_category: Dict[str, int] = {}
        by_risk: Dict[str, int] = {}
        by_discovery: Dict[str, int] = {}
        auth_count = 0
        declared_count = 0
        supported_count = 0
        unsupported_count = 0

        for ep in endpoints:
            if ep.declared_in_openapi:
                declared_count += 1
            if ep.supported:
                supported_count += 1
            else:
                unsupported_count += 1

            # Method
            m = ep.method.value
            by_method[m] = by_method.get(m, 0) + 1
            # Category
            cat = ep.category.value
            by_category[cat] = by_category.get(cat, 0) + 1
            # Risk
            risk = ep.risk.value
            by_risk[risk] = by_risk.get(risk, 0) + 1
            # Discovery
            disc = ep.discovered_by.value
            by_discovery[disc] = by_discovery.get(disc, 0) + 1
            # Auth
            if ep.authentication_required:
                auth_count += 1

        return cls(
            total_endpoints=len(endpoints),
            declared_operations_count=declared_count,
            supported_operations_count=supported_count,
            unsupported_probed_count=unsupported_count,
            by_method=by_method,
            by_category=by_category,
            by_risk=by_risk,
            by_discovery_method=by_discovery,
            authenticated_endpoints=auth_count,
            unauthenticated_endpoints=len(endpoints) - auth_count,
        )



# ---------------------------------------------------------------------------
# Scan metadata
# ---------------------------------------------------------------------------

class ScanMetadata(BaseModel):
    """
    Metadata describing the scan run that produced this catalogue.

    Stored at the top of the output file so consumers can trace provenance.
    """

    target_url: str = Field(..., description="Base URL that was scanned.")
    scan_started_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when the scan started.",
    )
    scan_completed_at: Optional[datetime] = Field(
        default=None,
        description="UTC timestamp when the scan completed.",
    )
    scanner_version: str = Field(
        default="1.0.0",
        description="Version of the discovery scanner that produced this catalogue.",
    )
    phase: str = Field(
        default="Phase 1 — API Discovery",
        description="Which phase of the multi-agent pipeline this catalogue belongs to.",
    )
    openapi_found: bool = Field(
        default=False,
        description="Whether an OpenAPI/Swagger spec was successfully parsed.",
    )
    openapi_url: Optional[str] = Field(
        default=None,
        description="URL from which the OpenAPI spec was retrieved.",
    )
    notes: List[str] = Field(
        default_factory=list,
        description="Free-text notes recorded during the scan (warnings, discoveries, etc.).",
    )


# ---------------------------------------------------------------------------
# Top-level catalogue model
# ---------------------------------------------------------------------------

class APICatalog(BaseModel):
    """
    Complete API catalogue produced by Phase 1.

    Structure
    ---------
    ::

        APICatalog
        ├── metadata        ← ScanMetadata
        ├── statistics      ← CatalogStats
        └── endpoints[]     ← List[EndpointModel]

    The ``endpoints`` list is the primary output consumed by Phase 2.
    All other fields provide context and summary information.
    """

    metadata: ScanMetadata = Field(..., description="Scan provenance and context.")
    statistics: CatalogStats = Field(
        default_factory=CatalogStats,
        description="Aggregated statistics over all endpoints.",
    )
    endpoints: List[EndpointModel] = Field(
        default_factory=list,
        description="All discovered API endpoints with full metadata.",
    )

    # ── Helpers ────────────────────────────────────────────────────────────────

    def endpoints_by_risk(self, risk: RiskLevel) -> List[EndpointModel]:
        """Return endpoints matching a specific risk level."""
        return [e for e in self.endpoints if e.risk == risk]

    def endpoints_by_category(self, category: EndpointCategory) -> List[EndpointModel]:
        """Return endpoints matching a specific category."""
        return [e for e in self.endpoints if e.category == category]

    def endpoints_by_method(self, method: HTTPMethod) -> List[EndpointModel]:
        """Return endpoints matching a specific HTTP method."""
        return [e for e in self.endpoints if e.method == method]

    def get_endpoint(self, method: str, path: str) -> Optional[EndpointModel]:
        """Retrieve a specific endpoint by method + path."""
        key = f"{method.upper()}:{path}"
        for ep in self.endpoints:
            if ep.unique_key == key:
                return ep
        return None

    def recompute_statistics(self) -> None:
        """Recompute and update the ``statistics`` field from current endpoints."""
        self.statistics = CatalogStats.from_endpoints(self.endpoints)

    def to_dict(self) -> Dict[str, Any]:
        """
        Serialise the full catalogue to a plain dict suitable for JSON/YAML output.

        Datetime objects are converted to ISO-8601 strings.
        """
        return self.model_dump(mode="json", exclude_none=False)

    def summary_lines(self) -> List[str]:
        """
        Return human-readable summary lines for console display.

        Returns
        -------
        List[str]
            Lines to be printed at the end of a scan run.
        """
        s = self.statistics
        lines = [
            "=" * 50,
            "Discovery Complete",
            "=" * 50,
            f"Endpoints Found : {s.total_endpoints}",
            "",
        ]
        for method, count in sorted(s.by_method.items()):
            lines.append(f"  {method:<8}: {count}")
        lines.append("")
        for cat, count in sorted(s.by_category.items()):
            lines.append(f"  {cat:<30}: {count}")
        lines.append("")
        for risk in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "UNKNOWN"]:
            count = s.by_risk.get(risk, 0)
            if count:
                lines.append(f"  {risk:<10} Risk : {count}")
        lines.append("")
        lines.append(f"  Auth Required   : {s.authenticated_endpoints}")
        lines.append(f"  No Auth         : {s.unauthenticated_endpoints}")
        lines.append("")
        for disc, count in sorted(s.by_discovery_method.items()):
            lines.append(f"  Discovered via {disc:<15}: {count}")
        lines.append("=" * 50)
        return lines
